# <auto-generated />
# Generated by scripts/Sync-LegacyCompatibility.ps1. Do not edit.

$script:LegacyCompatibilityManifestSchemaVersion = 1

# 旧識別子を採取した不変の v1.2.1 ソースを監査時に照合する。
# 互換性調査の対象リリースを固定する。
$script:LegacyCompatibilitySourceReleaseTag = 'v1.2.1'
# annotated tagをpeelしたv1.2.1 commitを一意に固定する。
$script:LegacyCompatibilitySourceCommit = '2ab0e9ce475d14f37a1fe8d149e07bd925d6451d'
# v1.2.1 annotated tag objectを監査時に照合する。
$script:LegacyCompatibilitySourceTagObject = 'c2e8f19716bfdbd669fb0a5ced1bcf59c62b280c'

# v1.2.1 のインストールを安全に発見し、in-place upgrade と清掃を行う。
# 既存 Inno Setup 登録を同一製品として更新し、登録済みパスを検証する。
$script:LegacyCompatibilityApplicationAppId = 'D1ACB787-2308-4AC4-91BD-A6A3856E7AF0'
# 旧 executable の VersionInfo と既知レイアウトを検証する。
$script:LegacyCompatibilityApplicationProductName = 'Even Terminal Supervisor'
# 旧プロセスと旧インストール先 executable の所有権を検証する。
$script:LegacyCompatibilityApplicationExecutableFileName = 'EvenTerminalSupervisor.exe'
# 旧 executable の VersionInfo が v1.2.1 の既知ビルドであることを検証する。
$script:LegacyCompatibilityApplicationExecutableOriginalFileName = 'EvenTerminalSupervisor.dll'
# 旧 executable の FileVersion を v1.2.1 に限定して所有権の誤認を防ぐ。
$script:LegacyCompatibilityApplicationExecutableFileVersion = '1.2.1.0'
# v1.2.1 の既定インストール先を発見する。
$script:LegacyCompatibilityApplicationInstallRootRelativeToLocalAppData = 'Programs\EvenTerminalSupervisor'
# 旧 settings、DPAPI token、transaction journal を移行する。
$script:LegacyCompatibilityApplicationDataRootRelativeToLocalAppData = 'EvenTerminalSupervisor'
# 旧 Inno Setup の uninstall support directory を検証して清掃する。
$script:LegacyCompatibilityApplicationUninstallSupportRootRelativeToLocalAppData = 'EvenTerminalSupervisor.Uninstall'
# 旧 startup preference を検出し、重複 shortcut を除去する。
$script:LegacyCompatibilityApplicationStartupShortcutFileName = 'Even Terminal Supervisor.lnk'
# 旧 install root が対象ユーザーと AppId に所有されることを検証する。
$script:LegacyCompatibilityApplicationOwnershipMarkerFileName = '.even-terminal-supervisor-install.json'
# HKCU の既存 Inno Setup 登録だけを参照する。
$script:LegacyCompatibilityApplicationUninstallRegistrySubKey = 'Software\Microsoft\Windows\CurrentVersion\Uninstall\{D1ACB787-2308-4AC4-91BD-A6A3856E7AF0}_is1'

# v1.2.1 の永続データを内容別に移行または保持する。
# 旧ユーザー設定を保全する。
$script:LegacyCompatibilityDataSettingsFileName = 'settings.json'
# 旧 DPAPI CurrentUser token を暗号化されたまま保全する。
$script:LegacyCompatibilityDataProtectedTokenFileName = 'token.dat'
# 中断済みの旧 install transaction を検出する。
$script:LegacyCompatibilityDataTransactionJournalFileName = 'install-transaction.json'
# 旧 rollback snapshot と recovery evidence を検出する。
$script:LegacyCompatibilityDataTransactionRecoveryDirectoryName = 'install-transactions'
# 中断済み v1.2.1 transaction journal を同じ検証規則で復旧する。
$script:LegacyCompatibilityDataTransactionSchemaVersion = '3'
# 旧 transaction が作成した一時 publish directory だけを検証して清掃する。
$script:LegacyCompatibilityDataInstallerPublishDirectoryPrefix = 'install-publish-'
# 旧 Tailscale Serve mapping と Firewall rule の所有権記録を継承する。
$script:LegacyCompatibilityDataAppliedSystemConfigurationFileName = 'applied-system-configuration.json'
# 未完了の旧system設定を安全側で再適用する。
$script:LegacyCompatibilityDataSystemConfigurationRequiredFileName = 'system-configuration-required'
# 旧diagnostic logging preferenceとrollback snapshotを保全する。
$script:LegacyCompatibilityDataDiagnosticLoggingMarkerFileName = 'diagnostic-logging.enabled'
# 旧log directoryをrollbackとuninstallの対象として厳密に識別する。
$script:LegacyCompatibilityDataLogDirectoryName = 'Logs'
# 旧data rootを継続利用する場合に既存log世代を保持する。
$script:LegacyCompatibilityDataLogFileName = 'supervisor.log'

# v1.2.1 の DPAPI token を再生成せずに引き継ぐ。
# DPAPI CurrentUser で保護された旧 token.dat の追加 entropy を再現する。
$script:LegacyCompatibilityCryptographyDpapiEntropyContext = 'EvenTerminalSupervisor/token/v1'

# 旧プロセスとの競合を避け、移行と清掃を排他的に行う。
# v1.2.1 のユーザー別 single-instance kernel object 群の基底名を再現する。
$script:LegacyCompatibilitySynchronizationInstanceScopeTemplate = 'Global\EvenTerminalSupervisor-{ownerSid}'
# 旧 supervisor の single-instance ownership を獲得または検出する。
$script:LegacyCompatibilitySynchronizationInstanceMutexTemplate = 'Global\EvenTerminalSupervisor-{ownerSid}-Mutex'
# 旧 supervisor の表示要求 event を識別する。
$script:LegacyCompatibilitySynchronizationInstanceShowEventTemplate = 'Global\EvenTerminalSupervisor-{ownerSid}-Show'
# 旧 supervisor へ安全な shutdown を要求する。
$script:LegacyCompatibilitySynchronizationInstanceShutdownEventTemplate = 'Global\EvenTerminalSupervisor-{ownerSid}-Shutdown'
# 旧 token.dat の読み書きと移行をユーザー別に排他する。
$script:LegacyCompatibilitySynchronizationTokenMutexTemplate = 'Global\EvenTerminalSupervisor-Token-{ownerSid}'
# 旧 install、uninstall、Tailscale、Firewall transaction と競合しないよう排他する。
$script:LegacyCompatibilitySynchronizationSystemTransactionMutex = 'Global\EvenTerminalSupervisor.SystemTransaction'

# 移行時に残存する v1.2.1 launcher の一時 IPC だけを識別する。
# 旧 bridge launcher の手動リセット launch gate を識別する。
$script:LegacyCompatibilityBridgeLaunchGateNameTemplate = 'Local\EvenTerminalSupervisor-Launch-{launchId}'
# 旧 bridge launcher が child PID を通知する current-user named pipe を識別する。
$script:LegacyCompatibilityBridgeLaunchPidPipeNameTemplate = 'EvenTerminalSupervisor-Pid-{launchId}'

# v1.2.1 setup が作成した一時 interactive task だけを検証して清掃する。
# 旧 setup の temporary per-user task を列挙する際の固定 prefix とする。
$script:LegacyCompatibilityInstallerTaskPrefix = 'Even Terminal Supervisor Installer'
# 32-hex transaction ID と許可済み purpose を含む完全な task 名を検証する。
$script:LegacyCompatibilityInstallerTaskNameTemplate = 'Even Terminal Supervisor Installer {transactionId} {purpose}'
# 旧 setup の設定検証 command task だけを許可する。
$script:LegacyCompatibilityInstallerTaskCommandPurpose = 'Command'
# 旧 setup の通常 launch task だけを許可する。
$script:LegacyCompatibilityInstallerTaskLaunchPurpose = 'Launch'
# 旧 setup の rollback recovery launch task だけを許可する。
$script:LegacyCompatibilityInstallerTaskRecoveryLaunchPurpose = 'RecoveryLaunch'

# v1.2.1 が所有するユーザー別 backend block rule だけを移行または削除する。
# owner SID suffix を付けた旧 committed Firewall rule を識別する。
$script:LegacyCompatibilityFirewallRulePrefix = 'Even Terminal Supervisor - block direct backend access'
# owner SID suffix を付けた旧 transaction 中の Firewall rule を識別する。
$script:LegacyCompatibilityFirewallTemporaryRulePrefix = 'Even Terminal Supervisor - pending backend block'

# supervisor 導入以前の EvenTerminalCodex task、launcher、plaintext token を厳密一致で移行する。
# 既知 action identity と一致した older scheduled task だけを停止、移行、削除する。
$script:LegacyCompatibilityOlderEvenTerminalCodexScheduledTaskName = 'EvenTerminalCodex'
# SID から解決した実 profile 配下の older data root を検証する。
$script:LegacyCompatibilityOlderEvenTerminalCodexLocalAppDataRootRelativeToProfile = 'AppData\Local\EvenTerminalCodex'
# older scheduled task action の標準 launcher path を検証する。
$script:LegacyCompatibilityOlderEvenTerminalCodexLocalAppDataLauncherRelativeToProfile = 'AppData\Local\EvenTerminalCodex\Start-EvenTerminalCodex.ps1'
# SID の User Shell Folders から解決した redirected Local AppData 配下の older launcher path を検証する。
$script:LegacyCompatibilityOlderEvenTerminalCodexLocalAppDataLauncherRelativeToLocalAppData = 'EvenTerminalCodex\Start-EvenTerminalCodex.ps1'
# 各ローカル drive 上に存在し得る旧 launcher path を厳密に検証する。
$script:LegacyCompatibilityOlderEvenTerminalCodexDriveLauncherRelativeToProfileDirectory = 'Users\{profileDirectory}\Apps\even-terminal\Start-EvenTerminalCodex.ps1'
# 標準 older data root 内の plaintext token candidate だけを移行する。
$script:LegacyCompatibilityOlderEvenTerminalCodexLocalAppDataTokenRelativeToProfile = 'AppData\Local\EvenTerminalCodex\token.txt'
# 各ローカル drive 上の既知旧 root 内にある plaintext token candidate だけを移行する。
$script:LegacyCompatibilityOlderEvenTerminalCodexDriveTokenRelativeToProfileDirectory = 'Users\{profileDirectory}\Apps\even-terminal\token.txt'
# older scheduled task action が標準 PowerShell 7 executable を使うことを検証する。
$script:LegacyCompatibilityOlderEvenTerminalCodexPowerShellRelativeToProgramFiles = 'PowerShell\7\pwsh.exe'
# older scheduled task または process の引数を完全一致で検証する。
$script:LegacyCompatibilityOlderEvenTerminalCodexLauncherArgumentsTemplate = '-WindowStyle Hidden -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -File "{launcherPath}"'
# older token candidate の file name を厳密に検証する。
$script:LegacyCompatibilityOlderEvenTerminalCodexPlaintextTokenFileName = 'token.txt'
